# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 11:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0002_auto_20171110_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter a the Campaign's Geo (e.g. Russia, Spain and etc.)", max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='geo',
            field=models.ManyToManyField(help_text='Select A Geo For This Campaign', to='advertisers.Geo'),
        ),
    ]
