# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0003_auto_20171111_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Browser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter a the Campaign's Browser (e.g. Google Chrome, Safari and etc.)", max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='browser',
            field=models.ManyToManyField(help_text='Select A Browser For This Campaign', to='advertisers.Browser'),
        ),
    ]
