# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0004_auto_20171111_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter a the Campaign's Target Language (e.g. Eglish, Spanish and etc.)", max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_language',
            field=models.ManyToManyField(help_text='Select A Target Language For This Campaign', to='advertisers.TargetLanguage'),
        ),
    ]
