# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0006_auto_20171111_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='target_language',
            field=models.ManyToManyField(help_text='Select A Target Language For This Campaign', related_name='target_language', to='advertisers.Language'),
        ),
    ]
