# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0007_campaign_target_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter a the Campaign's Device (e.g. Desktop, Mobile and etc.)", max_length=200)),
            ],
        ),
    ]
