# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0008_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='device',
            field=models.ManyToManyField(help_text='Select A Device For This Campaign', to='advertisers.Device'),
        ),
    ]
