# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0009_campaign_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='user_utm',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
