# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0010_campaign_user_utm'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='clicks',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='cpc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='campaign',
            name='impressions',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
