# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0013_auto_20171111_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='browser',
            field=models.ManyToManyField(blank=True, help_text='Select A Browser For This Campaign (default all browsers)', null=True, to='advertisers.Browser'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='device',
            field=models.ManyToManyField(blank=True, help_text='Select A Device For This Campaign (default all devices)', null=True, to='advertisers.Device'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='geo',
            field=models.ManyToManyField(blank=True, help_text='Select A Geo For This Campaign (default all geos)', null=True, to='advertisers.Geo'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target_language',
            field=models.ManyToManyField(blank=True, help_text='Select A Target Language For This Campaign (default all languages)', null=True, related_name='target_language', to='advertisers.Language'),
        ),
    ]
