# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0014_auto_20171111_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teaser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('impressions', models.BigIntegerField(default=0)),
                ('clicks', models.BigIntegerField(default=0)),
                ('spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cpc', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
            ],
        ),
        migrations.AlterField(
            model_name='campaign',
            name='browser',
            field=models.ManyToManyField(blank=True, help_text='Select A Browser For This Campaign (default all browsers)', to='advertisers.Browser'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='device',
            field=models.ManyToManyField(blank=True, help_text='Select A Device For This Campaign (default all devices)', to='advertisers.Device'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='geo',
            field=models.ManyToManyField(blank=True, help_text='Select A Geo For This Campaign (default all geos)', to='advertisers.Geo'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target_language',
            field=models.ManyToManyField(blank=True, help_text='Select A Target Language For This Campaign (default all languages)', related_name='target_language', to='advertisers.Language'),
        ),
        migrations.AddField(
            model_name='teaser',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='advertisers.Campaign'),
        ),
        migrations.AddField(
            model_name='teaser',
            name='status',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='advertisers.Status'),
        ),
    ]
