# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0015_auto_20171111_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaser',
            name='cpc',
        ),
    ]
