# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0021_teaser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaser',
            name='image',
            field=models.ImageField(upload_to='teasers/'),
        ),
    ]
