# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0022_auto_20171112_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaser',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
