# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0023_teaser_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teaser',
            old_name='url',
            new_name='link',
        ),
    ]
