# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0024_auto_20171112_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teaser',
            old_name='link',
            new_name='url',
        ),
    ]
