# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='columns',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=3, help_text='Enter Widget Columns (Number between 1 and 3'),
        ),
        migrations.AddField(
            model_name='widget',
            name='rows',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1, help_text='Enter Widget Rows (Number between 1 and 3'),
        ),
    ]
