# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0001_initial'),
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='language',
        ),
        migrations.AddField(
            model_name='widget',
            name='language',
            field=models.ManyToManyField(related_name='widget_language', to='advertiser.Language'),
        ),
    ]
