# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0001_initial'),
        ('publisher', '0002_auto_20171115_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='language',
        ),
        migrations.AddField(
            model_name='widget',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='widget_language', to='advertiser.Language'),
        ),
    ]
