# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0003_auto_20171115_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='geo',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='language',
        ),
    ]
