# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgetgenerator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientinfo',
            name='city',
        ),
        migrations.RemoveField(
            model_name='clientinfo',
            name='country',
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='country_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
