# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 08:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Browser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Choose a Browser (e.g. Google Chrome, Safari and etc.)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user_utm', models.CharField(blank=True, max_length=400)),
                ('impressions', models.BigIntegerField(default=0)),
                ('clicks', models.BigIntegerField(default=0)),
                ('spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cpc', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('browser', models.ManyToManyField(blank=True, help_text='Select A Browser For This Campaign (default all browsers)', to='advertiser.Browser')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Choose a Category (e.g. WeightLoss, Health And Beauty and etc.)', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Choose a Device (e.g. Desktop, Mobile and etc.)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Geo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Choose a Geo (e.g. Russia, Spain and etc.)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Choose a Language (e.g. English, Spanish, Russian etc.)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Choose a Status (e.g. Active, Paused and etc.)', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'statuses',
            },
        ),
        migrations.CreateModel(
            name='Teaser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='teasers/')),
                ('url', models.URLField(default='')),
                ('impressions', models.BigIntegerField(default=0)),
                ('clicks', models.BigIntegerField(default=0)),
                ('spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='advertiser.Campaign')),
                ('status', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='advertiser.Status')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='category',
            field=models.ForeignKey(default=1, help_text='Select A Category For This Campaign', on_delete=django.db.models.deletion.CASCADE, to='advertiser.Category'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='device',
            field=models.ManyToManyField(blank=True, help_text='Select A Device For This Campaign (default all devices)', to='advertiser.Device'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='geo',
            field=models.ManyToManyField(blank=True, help_text='Select A Geo For This Campaign (default all geos)', to='advertiser.Geo'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_language', to='advertiser.Language'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='advertiser.Status'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_language',
            field=models.ManyToManyField(blank=True, help_text='Select A Target Language For This Campaign (default all languages)', related_name='campaign_target_language', to='advertiser.Language'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
