# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geo',
            name='code',
            field=models.CharField(help_text='Choose a Geo (e.g. Russia, Spain and etc.)', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='geo',
            name='name',
            field=models.CharField(help_text='Choose a Geo (e.g. Russia, Spain and etc.)', max_length=44, null=True),
        ),
    ]
