# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0002_auto_20171115_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Choose a Language Code (e.g. en, es-ni, ru etc.)', max_length=5)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='advertiser.Language')),
            ],
        ),
    ]
