# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0003_languagecodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languagecodes',
            name='language',
        ),
        migrations.AddField(
            model_name='language',
            name='code',
            field=models.CharField(default='en', help_text='Choose a Language Code (e.g. en, es-ni, ru etc.)', max_length=5),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(default='English', help_text='Choose a Language (e.g. English, Spanish, Russian etc.)', max_length=200),
        ),
        migrations.DeleteModel(
            name='LanguageCodes',
        ),
    ]
