# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0004_auto_20171115_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geo',
            name='code',
            field=models.CharField(help_text='Choose a Geo (e.g. ES, IT and etc.)', max_length=2, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(default='en', help_text='Choose a Language Code (e.g. en, es-ni, ru etc.)', max_length=5, unique=True),
        ),
    ]
