# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 11:19
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0006_auto_20171115_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaser',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[1920, 1080], upload_to='teasers/'),
        ),
    ]
