# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0007_auto_20171116_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaser',
            name='image',
            field=models.ImageField(height_field=444, upload_to='teasers/', width_field=328),
        ),
    ]
