# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0008_auto_20171116_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaser',
            name='image',
            field=models.ImageField(upload_to='teasers/'),
        ),
    ]
