# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 16:04
from __future__ import unicode_literals

import advertiser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0009_auto_20171116_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaser',
            name='image',
            field=models.ImageField(upload_to=advertiser.models.update_filename),
        ),
    ]
